minVersion: "0.20.0"

github:
  owner: getsentry
  repo: wal2json
# TODO: Add a changelog
changelogPolicy: none

artifactProvider:
  name: github
statusProvider:
  name: github

preReleaseCommand: ''

targets:
  - name: github

requireNames:
  - /^wal2json-Linux-x86_64.so$/
