name: Binary Release Build

on:
  push:
    branches:
      - release/**
      - master
  pull_request:
    

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
    
      - name: Build in Docker (x86-64)
        # Add more of these steps to support other architectures
        run: |
          docker build --build-arg DOCKER_ARCH=amd64 -t getsentry/postgres_wal2json:build --target build .
          docker create --name=postgres_wal2json getsentry/postgres_wal2json:build
          docker cp postgres_wal2json:/usr/local/lib/postgresql/wal2json.so ./wal2json-Linux-x64.so

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: wal2json-Linux-x64.so
