name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Docker Set up
        run: |
          docker build -t getsentry/postgres_wal2json  .
          docker run -e POSTGRES_PASSWORD=password -d --name postgres getsentry/postgres_wal2json  -c wal_level=logical -c max_replication_slots=1 -c max_wal_senders=1
          docker exec postgres pg_isready --timeout 10 -U postgres
      - name: wal2json tests
        run: |
          docker run postgres --entrypoint make installcheck
